### ISSUE TITLE
Unable to use with react native

### ISSUE THREAD

**Issue by kgritesh** [rauschma/enumify#10]
From what i can gather `enumify` has a dependency of `babel-preset-es2015`which kind of conflicts with react-native default presets and hence i am unable to use this with react-native currently.  More information can be found from here https://github.com/facebook/react-native/issues/5747#issuecomment-192356656. Currently i am forced to locally copy this code in my source code to use this library. Any help would be appreciated. Thanks

**Comment by afilp** [comment]
+1

**Comment by jjzazuet** [comment]
Same. Thanks!

**Comment by isingh** [comment]
+1

**Comment by larryranches** [comment]
+1

**Comment by bondia** [comment]
+1

**Comment by eapostol** [comment]
+1

**Comment by mswokk** [comment]
+1

**Comment by fabriziocacicia** [comment]
+1

**Comment by hhunaid** [comment]
Someone who is struggling to make it work on iOS 8 and Android you can put
```jsx
import 'core-js/es6/set';
import 'core-js/es6/symbol';
import 'core-js/fn/symbol/iterator';
```
on the top of your `index.js`
