### ISSUE TITLE
Remove src/ from .npmignore

### ISSUE THREAD

**Issue by temapavloff** [rauschma/enumify#12]
Hi Axel,

In our project we use Bable, configured in SystemJS mode.

So, we cannot use Enumify installed from npm, because it's transpiled in CommonJS mode.

Can you remove `src/` directory from `.npmignore` to make possible use original es6 source with custom babel configuration.

Thank you

**Comment by omeid** [comment]
Just install with the repo url.

**Comment by temapavloff** [comment]
@omeid, i've tried it with npm version 2.13 and with the latest, `.npmignore` just still work.
