### ISSUE TITLE
IE10 Error even with babel polyfill

### ISSUE THREAD

**Issue by yleviel** [rauschma/enumify#13]
I'm using babel + polyfill.  The following works in all browsers (IE11+), but has a showstopper issue in IE9 and 10:

Error: "Object doesn't support property or method 'initEnum' "
Code: 

```
import {Enum} from 'enumify';
export default class Directions extends Enum {}

EventType.initEnum([
  'North',
  'South',
  'East',
  'West'
]);

```

**Comment by ghost** [comment]
Hi, I've just come across this exact issue as well. Did you ever come up with a solution to this?

**Comment by yleviel** [comment]
No, we simply chose to not support browsers less than IE11

**Comment by armano2** [comment]
@yleviel @Flashwit http://babeljs.io/docs/plugins/transform-proto-to-assign/
its babel fault 🍡 

see https://babeljs.io/docs/usage/caveats/#internet-explorer

**Comment by OrenMe** [comment]
@armano2 so with transform-proto-to-assign it will work?

**Comment by armano2** [comment]
@OrenMe yes

**Comment by OrenMe** [comment]
Thanks @armano2

**Comment by 512guanguan** [comment]
@armano2 I have added transform-proto-to-assign like this in .babelrc file
`{
  "plugins": ["transform-proto-to-assign"]
}`
but  it still doesn't work

**Comment by aniude** [comment]
I found that the https://github.com/babel/babel/issues/8050 is the same problem about the babel and the last the author give the answer.

Just install proto-polyfill add like this:
`import 'proto-polyfill';`

then IE10 is workaround.
