### ISSUE TITLE
Typings for TypeScript?

### ISSUE THREAD

**Issue by LMFinney** [rauschma/enumify#18]
I'd like to depend on this project in a TypeScript app, but I haven't found typings for it here or on DefinitelyTyped. Have types been defined for this? Or am I just missing something obvious?

Thanks

**Comment by LMFinney** [comment]
Note: I ended up forking and creating my own TypeScript version: [ts-enums](https://github.com/LMFinney/ts-enums). The API isn't identical, but it serves much of the same purpose for my needs.

**Comment by DrummerHead** [comment]
https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by LMFinney** [comment]
@DrummerHead The enums that TypeScript provides are much simpler and have fewer feature than what this repo or ts-enums provides. It's a different concept.
