### ISSUE TITLE
package.json main points to inexistent

### ISSUE THREAD

**Issue by staltz** [rauschma/enumify#2]
I npm installed enumify, and I went to `node_modules/enumify`, and it had this folder structure:
- lib (dir)
- .npmignore (file)
- package.json (file)
- README.md (file)

Yet, package.json has:

``` js
  ...
  "main": "./src/enumify.js",
  ...
```

Which makes it unusable. 
Enumify version 1.0.3.
Npm version 3.3.12.
Node version 5.4.1.

**Comment by rauschma** [comment]
Thanks! Fixed now (v.1.0.4)
