### ISSUE TITLE
Adding support with node.js modules?

### ISSUE THREAD

**Issue by adibiton** [rauschma/enumify#20]
Hi,
Sorry if it not the right place, but can the library be supported with common js module system (adding 
'module.exports = Enum' at the end of the script)?

Thanks

**Comment by coagmano** [comment]
@adibiton If you look at the built code published on npm, you'll see that `Enum` is placed on the `exports` object for CJS compatability:

```
var Enum = exports.Enum = function () {
```
Which means you can require no problem. Easier with destructing:
```
var { Enum } = require('enumify');
```

**Comment by adibiton** [comment]
@coagmano got it, thanks!
