### ISSUE TITLE
Not able to use with Vue application

### ISSUE THREAD

**Issue by kinow** [rauschma/enumify#21]
Hi,

I am using `enumify` 1.x in a [Vue application](https://github.com/cylc/cylc-ui). This morning tried updating to `enumify` 2.x. I had to rewrite the enums with the new syntax, which looks great IMO.

In our case, we have the statuses of tasks in a workflow manager. These statuses are strings, so I used the suggestion of the documentation defining an enum like:

```js
class TaskState extends Enumify {
  static running = new TaskState('running');
  static succeeded = new TaskState('succeeded');
  static _ = this.closeEnum();
  constructor(value) {
    super();
    this.value = value;
  }
}
```

This works fine in the IDE, but when running the Vue CLI build command I get the error "Missing class properties transform", more below:

```bash
 error  in ./src/model/TaskState.model.js

Syntax Error: SyntaxError: /home/kinow/Development/python/workspace/cylc-ui/src/model/TaskState.model.js: Missing class properties transform.
   7 |   // NOTE: the order of the enum values is important to calculate the group states in the UI. Items at
   8 |   // the top of the list have preference over the items below in the algorithm.
>  9 |   static submitFailed = new TaskState('submit_failed')
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  10 |   static failed = new TaskState('failed')
  11 |   static expired = new TaskState('expired')
  12 |   static submitRetrying = new TaskState('submit_retrying')


 @ ./src/utils/tasks.js 2:0-48 8:30-39 8:54-63 8:72-81 8:91-100 8:112-121 8:131-140 8:148-157 8:174-183 8:194-203 8:215-224 8:233-242 8:252-261 8:268-277 19:71-80
 @ ./src/components/cylc/tree/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--20-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Tree.vue?vue&type=script&lang=js&
 @ ./src/views/Tree.vue?vue&type=script&lang=js&
 @ ./src/views/Tree.vue
 @ ./src/views lazy ^\.\/.*\.vue$ namespace object
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

```

It looks like this could be something in my local environment, possibly with Vue Loader/babel not being happy with the class static fields.

I will dig more later to investigate, but reporting the issue here just in case anybody else has a similar problem, or even a possible workaround.

Likely not an issue in the library? But if I find a workaround that suggests ES2015 users may need some extra configuration in Babel, I'd be happy to provide a PR for the docs and close this issue :+1: 

Cheers
Bruno

**Comment by kinow** [comment]
For the time being I'm pinning the dependency to 1.0.4 just to finalize the other dependencies update (which is fixing some security updates). But will revisit it soon.

**Comment by rauschma** [comment]
This Babel plugin should do the trick: https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

**Comment by kinow** [comment]
Thanks @rauschma ! I'm still working through other updates, but I think I can test this one today/tomorrow.

**Comment by kinow** [comment]
Adding the Babel plugin fixed it. thanks @rauschma !

**Comment by kinow** [comment]
(if others using Vue have a similar problem, see linked issue above in case you have issues with the Istanbul loader as their current release doesn't load babel plugins; my workaround was to use a yarn resolution)
