### ISSUE TITLE
Accessing undefined enums

### ISSUE THREAD

**Issue by mlucool** [rauschma/enumify#6]
I love the concept. But, after playing with it, I ran across a non-starter that I am hoping you have an idea on how to solve.

Undefined Variables

```
import {Enum} from 'enumify';
class MyType extends Enum {}
MyType.initEnum(['FOO', 'BAR']);
let x;
if(x === MyType.SOME_TYPO) {
console.log('Found X!');
}
```

Ideally, I'd like this to be a compile time (i.e. babel) or static (i.e. ESLint) check or at the very least get syntax highlighting in Webstorm. Any suggestions?

**Comment by tp** [comment]
Does it throw a runtime exception for invalid enum cases yet?

I once had great success using a [Proxy](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy) for a similar case, to intercept access to unknown fields.

**Comment by mlucool** [comment]
@tp that is a good idea for run time checks

**Comment by doublemarked** [comment]
+1 @mlucool Exactly what I was thinking too. @tp I also considered using a Proxy to lock things down. Did you publish anything with that?

**Comment by zyrolasting** [comment]
@mlucool It would be awkward to expect a parser to detect something that's not formally part of the grammar. You could of course extend ESLint to check if `MyType.WHATEVER` appears in a call to `initEnum`. But this is made trickier by the fact that `initEnum` also accepts objects as an argument, or even no argument at all. And what about nested Enums? Would you rather account for (untested and enterprise-y) input like what's below, or just carefully watch what you type?

```
import {Enum} from 'enumify';
import resourceTypes from 'somewhere/else'; // Surprise array linters can't see!

console.log(resourceTypes); // ['BOOKS', 'MUSIC', 'VIDEO']

class Events extends Enum {}
class CreateEvents extends Enum {}
class ReadEvents extends Enum {}
class UpdateEvents extends Enum {}
class DeleteEvents extends Enum {}

CreateEvents.initEnum(resourceTypes);
ReadEvents.initEnum(resourceTypes);
UpdateEvents.initEnum(resourceTypes);
DeleteEvents.initEnum(resourceTypes);
Events.initEnum({
    CREATE: CreateEvents,
    UPDATE: UpdateEvents,
    READ: ReadEvents,
    DELETE: DeleteEvents,
});


/* ... 500+ lines ... */

Events.CREATE.MSUIC // Oops. 
```

Each case requires its own analysis, which is honestly a bit much to handle given the limited scope of the project. If you are only going to care about simpler cases anyway, I'd just note the general coding habits in the source and write a assumption-laden ~50 line one-off that checks all suspect files in a pre-commit hook or something. That's the best compromise between "static" and "fast" as you are going to get until JS actually makes enums part of the language.

**Comment by doublemarked** [comment]
@zyrolasting I think runtime exceptions, as with a mistyped function name, would be appropriately consistent and also guard against hidden errors caused by undefined values, which is a large part our the potential benefit of an enum type. In fact, perhaps an enum lib like enumify could directly generate functions instead of primitives.

**Comment by zyrolasting** [comment]
@doublemarked I understand where you are coming from. I'm only speaking in the context of OP, where @mlucool was asking about detecting errors before running code, which won't happen until you get TypeScript, ESLint or some other auditor involved.

But in runtime, yes, a Proxy + exceptions will suffice when intercepting incorrect names.
