### ISSUE TITLE
Simplify API for easy cases

### ISSUE THREAD

**Issue by danielkcz** [rauschma/enumify#9]
I mean is it necessary to have the boilerplate of creating the class? Cannot we do something like `const Color = Enum.create('RED', 'GREEN', 'BLUE')`. Since class is an expression, having factory function like this should work, right?

```
Enum.create = function(...names) {
    const enum = class EnumClass extends Enum {}
    enum.initEnum(...names);
    return enum;
}
```

If this isn't possible for some reason, then perhaps something like `class Color extends Enum.create('RED', 'GREEN', 'YELLOW') {}`. Although that's not that pretty anymore.

**Comment by Pencroff** [comment]
No way to achieve this kind of functionality, because it's no way to make dynamic names for ES6 classes.
Look at http://stackoverflow.com/questions/33605775/es6-dynamic-class-names.

``` javascript
const Color = Enum.create('RED', 'GREEN', 'BLUE')
Color.RED.toString() // enum.RED
```

**Comment by danielkcz** [comment]
@Pencroff this issue wasn't about dynamic class names really and I don't think it matters that much. I am not using this lib anymore as I generally don't use ES6 classes.
